[gcp_service_account]
type = "service_account"
project_id = "neat-talent-394322"
private_key_id = "9ebc5bc04590a12720b3cac1e18d90bbf2f382cb"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD49i2kJzxAznHz
... your key continues ...
-----END PRIVATE KEY-----"""
client_email = "mike-42@neat-talent-394322.iam.gserviceaccount.com"
client_id = "110468122802858361737"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mike-42%40neat-talent-394322.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[apify_token]
apify_token = "apify_api_Ubl1gH7MALA2UuhzlvsAJNQYRAzp7A4sUHRz"
